[project]
name = "dags"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "apache-airflow==2.10.5",
  "apache-airflow-providers-postgres>=6.0.0",
  "pandas>=2.1.4",
  "psycopg2-binary>=2.9.11",
  "requests>=2.33.1",
  "office365-rest-python-client>=2.6.2",
  "polars>=1.28.1",
  "pyarrow>=23.0.1",
  "pyodbc>=5.3.0",
  "python-dotenv>=1.2.2",
  "sqlalchemy>=1.4.54",
  "xlsxwriter>=3.2.9",
  "apache-airflow-providers-microsoft-mssql>=4.3.3",
]

[dependency-groups]
dev = ["taskipy", "ruff", "pytest", "pytest-cov"]

[tool.taskipy.tasks]
lint = "uv run ruff check"
pre_format = "uv run ruff check --fix"
format = "uv run ruff format"
run = "uv run streamlit run Home.py"
pre_test = "uv run task lint"
test = "uv run pytest -s -x --cov=./ -vv"
post_test = "uv run coverage html"
build = "docker build -t ${DOCKER_REGISTRY:-}transferencia-modelo:latest ."
pre_push = "uv run task build"
push = "docker push ${DOCKER_REGISTRY:-}transferencia-modelo:latest"
pre_dw = "uv run task build"
dw = "docker compose up --watch"
docker = "docker compose up -d"

[tool.black]
color = true
line-length = 100
target-version = ['py313']
skip-string-normalization = true

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.ruff]
line-length = 100
